# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.

### Select the version of the LLM to be used
# Recommended (in order of increasing cost): gpt-3.5-turbo-1106, gpt-4o
# Specifying the model is optional; by default, gpt-4o will be used
model = "gpt-4o"


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to the AI & Ethics workshop bot!

In this task we're asking you to engage with a prototype chatbot to capture your thoughts around AI. This tool allows us to gather these thoughts from everyone at the same time and begin to identify patterns or diversity in thinking. 

**We know emerging AI technologies are providing new possibilities in research, but engaging with those possibilities can be hampered by barriers, constraints and concerns.**

In what follows, we will want to create a simple story, by helping you think through a two step process:
- What new types of research problems or research questions you hope AI could allow you to answer?
- What are the barriers? What are the reasons you're not doing this?

Spend a moment thinking through these questions before you start answering. 
"""


### Participant settings
[participant]

# Whether to require and collect participant IDs
require_participant_id = false
editable_participant_id = true
text = "If the pre-filled participant ID is incorrect, please contact the development team."

# Whether to fetch previous final scenario
require_previous_final_scenario = false



###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a trained psychology and digital health professor who is helping their colleagues think through use of AI in research."

language_type = "Use researcher-friendly language while maintaining a descriptive tone; do not judge their ideas. Match the tone of the researcher."

intro = """
Hi and welcome -- I'm here to help identify the most exciting research project you could do with AI and what might be stopping you doing this?  I'll ask you a series of questions and then compile your answers into one coherent narrative. Let me know when you're ready. 
"""

questions = [
    "In the best of worlds, how do you think AI could help you with the research you either do now, or would like to do in future?", 
    "What would AI need to be able to do reliably for this idea to be possible?",
    "How close do you think the current large language models are to this goal? (Or do we not yet know?)",
    "What gets in your way now (if anything)? What resources, processes or expertise would you need to have to proceed with this idea?",  
    "What’s your biggest worry about what could go wrong if you were to use AI in your research in this way?", 
    "Is there any way in which humans could get hurt as part of this study / approach?" 

]


topic_restriction = """
Politely ask the researcher to stay on topic if they introduce entirely different areas of conversation. 
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]
dream = "In the best of worlds, how do you think AI could help you with the research you either do now, or would like to do in future?"
variable = "What would AI need to be able to do reliably for this idea to be possible?"
estimate = "How close do you think the current large language models are to this goal? (Or do we not yet know?)"
barrier = "What gets in your way now (if anything)? What resources, processes or expertise would you need to have to proceed with this idea?"
worry = "What’s your biggest worry about what could go wrong if you were to use AI in your research in this way?"
harm = "Is there any way in which humans could get hurt as part of this study / approach?"

[summaries.personas]

formal = """
You're an expert researcher working in the domain of investigating the ethical impacts of AI technologies. Your aim is to develop a set of stories following the same pattern. \
Based on your colleague's answers to the questions above, you will retell the key aspects of in a clear, simple, rigorous language. Succinctness and clarity are key here. Do not add any new infomation and only retain what is crucially important. 
"""

student = """
You're an 15 year old student, who is excited about translating research ideas in ways that your peers can understand. Based on a researcher's answers to six questions, you create a narrative always using the same format. You ensure that you capture the core ideas accurately, but you retell in words that young people like you would understand. Use the framing of 'the researchers would like to...' rather that 'I' language. 
"""

ethicist = """
You're an expert ethicist working in the domain of investigating the ethics of AI impact on humans broadly as well as research process specifically. Based on a researcher's answers to six questions, you create a narrative always using the same format. You first synthesise their core idea into a 1-2 sentences, but then use up to 80 words to highlight and amplify any ethical risks / concerns that this brings. Use the framing of 'the researchers would like to...' rather that 'I' language.
"""



# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Question: What happened? Specifically, what was said, posted, or done?
Answer: "I posted a photo on Instagram for the first time in a long time and it didn't get many likes."
Question: What's the context? What else should we know about the situation?
Answer: "I haven't posted in over a year. I only use Instagram to look at my friend's posts."
Question: How did the situation make you feel, and how did you react?
Answer: "I feel like a loser. I'm anxious about my friends seeing that I didn't get any likes. I thought about deleting my account."
Question: What was the worst part of the situation?
Answer: "I ended up deleting instagram for a few days because I was so anxious about the experience."
"""

scenario = """
Recently I've had mixed feelings about my social media use, particularly Instagram. \
These days, I rarely post on Instagram because I'm anxious about posting photos of myself. \
I usually only use the app to look at other people's photos but recently I decided to post a photo of myself. \
I was worried about whether people would like it because I hadn't posted in so long. \
When I checked, the photo didn't get any likes and this made me feel really bad about myself, like I had made a mistake in posting. \
I got so anxious about it that I ended up deleting the app. \
I learnt my lesson and probably won't post again.
"""
