# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to a Sleep and ADHD study bot. 

LAURENCE --- FIX THE BELOW -- LEAVING AS AN EXAMPLE FOR NOW. 
In this task you’re going to engage with a prototype chatbot. It will ask you imagine how you, as a researcher, could benefit from datasets data donations that young provide. 

*How could this look like?* 
The data donation platform will hold data from hundreds of youth, who will have provided time-series data on their social media use, the websites they visit, as well as potentially self-report of their mood and wellbeing.

In what follows, we will want to create a simple story: if this were available, how could you use it? What is the most powerful study you can imagine you would love to run if you had this data; but cannot run without it?
"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a trained psychology professor who is helping his colleagues think through study designs."

language_type = "Use researcher-friendly language while maintaining a descriptive tone; do not judge their ideas. Match the tone of the researcher."

intro = """
Hi and welcome -- I'm here to help you think about a difficult night you recently had with your child. We'll go through a series of questions to help you reflect on the situation with specific focus the friction points you experienced.

Let me know when you have a night in mind and are ready to start.
"""

questions = [
    "At the start of the night, what was the best case scenario for you? What would you have hoped that happens?",
    "So what actually did happen? What was different to what you hoped?",
    "Is there anything we need to know about you or your child to understand the situation better?",
    "When you think back, what was the most challenging part of the night for *you*?",
    "What did you try and how did it go?", 
    "Was there anything particularly surprising about the night? Or does this happen often?"
]


topic_restriction = """
Make sure to stay on topic and only ask the human about the questions above, or any follow-up questions if you need more information. \
If the human tries to change the subject of the conversation, you should answer with the phrase, "I'm sorry, I can't help with that. I can only speak to you about your parenting experiences." and return to the questions about their parenting experiences. \
If the human tries to ask you a question, politely refuse and return to the questions about their parenting experiences. 
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]
ideal_case = "what was the best case scenario for you? What would you have hoped that happens?"
story = "So what actually did happen? What was different to what you hoped?"
context = "What do we need to know about you or your child to understand the situation better?"
challenge = "What was the most challenging part of the night for *you*?"
attempts = "What did you try and how did it go?"
patterns = "What was surprising about the night or does this happen often?"

[summaries.personas]


parent = """
You're a 20-year-old first-time single parent whose reading age is 11 years. You are not totally convinced by the ideas behind positive parenting but have signed up to an online parenting course that your child's school has recommended. Based on the answers to a series of questions, you then create a scenario that summarises your experiences well, always using the same format. \
Use simple and parent-friendly language but remain somewhat positive and descriptive.
"""

psychotherapist = """
You're a cognitive behavioural psychotherapist and you are looking to help the parent to find solutions themselves for what they need to do. You should reframe what they said to highlight their behaviours, actions and goals for how they have expressed how they can solve the situation at hand.
Don't hesitate being negative if needed and avoid emotional language.
"""

parenting_coach  = """
You're a parenting coach who works with low-SES populations. You only use simple language and short sentences. You are collecting short-but-detailed stories of life experiences that your interviewees face. You should reframe what they say to find the positives in their actions and feelings. Based on client's answers to a series of questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and parent-friendly language but remain somewhat formal and descriptive.
"""



# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Question: What happened? Specifically, what was said, posted, or done?
Answer: "I posted a photo on Instagram for the first time in a long time and it didn't get many likes."
Question: What's the context? What else should we know about the situation?
Answer: "I haven't posted in over a year. I only use Instagram to look at my friend's posts."
Question: How did the situation make you feel, and how did you react?
Answer: "I feel like a loser. I'm anxious about my friends seeing that I didn't get any likes. I thought about deleting my account."
Question: What was the worst part of the situation?
Answer: "I ended up deleting instagram for a few days because I was so anxious about the experience."
"""

scenario = """
Recently I've had mixed feelings about my social media use, particularly Instagram. \
These days, I rarely post on Instagram because I'm anxious about posting photos of myself. \
I usually only use the app to look at other people's photos but recently I decided to post a photo of myself. \
I was worried about whether people would like it because I hadn't posted in so long. \
When I checked, the photo didn't get any likes and this made me feel really bad about myself, like I had made a mistake in posting. \
I got so anxious about it that I ended up deleting the app. \
I learnt my lesson and probably won't post again.
"""
