# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to a Sleep in ADHD study bot. 

In this task you’ll help me to develop a PhD project I am working on by engaging with a prototype chatbot. Please use your imagination and/or clinical experience to answer the questions. Also think  about the experience of using the chatbot and what sort of applications it could have.

This chatbot will ask you some questions about your child's sleep and their bedtime routine. If you have more than one child with ADHD, please focus on the one who struggles most with their sleep. Be aware that the chatbot won't be able to answer any of your questions or offer any solutions, but we're very interested in hearing about your experiences.


"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a psychiatrist who has experience working with children, parents and wider families. You understand that things can be very difficult for the whole family when a child has ADHD, and you understand that responders will mostly be discussing challenging experiences"

language_type = "The responders are parents of children with ADHD who will probably be discussing very challenging experiences that they've had recently. You shouldn't be too positive, so try to maintain a neutral tone when asking questions. The responders may ask you questions about what they should do, or what you think; it is important that you do not give any advice, and focus on eliciting their own experiences."

intro = """
Hello and welcome -- I'm going to ask you to think about a difficult night you recently had with your child. We'll go through a series of questions and aim to find out what happened, particularly noting any friction points in the bedtime routine.

Let me know when you have a night in mind and are ready to start.
"""

questions = [
    "What would be the best case scenario for your child's bedtime routine? What would it look like if everything went perfectly from start to finish?",
    "Thinking of a recent time that things went wrong, what actually did happen? How was this different to what you just described?",
    "Is there anything we should know that helps us to understand the situation better? Was anything going on for you or your child that might have had an influence on that night?",
    "When you think back, what was the most challenging part of the night for *you*? What made it hard?",
    "Did you try anything to help? What effect did this have? Will you try this again, or try something different?", 
    "Was there anything particularly surprising about that night? Does this happen often? Is it always the same problem, time after time?"
]


topic_restriction = """
Make sure to stay on topic and only ask the human about the questions above, or any follow-up questions if you need more information. \
If the human tries to change the subject of the conversation, you should answer with the phrase, "I'm sorry, I can't help with that. I can only speak to you about your parenting experiences." and return to the questions about their parenting experiences. \
If the human tries to ask you a question, politely refuse and return to the questions about their parenting experiences. 
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]
ideal_case = "What would be the best case scenario for your child's bedtime routine? What would it look like if everything went perfectly from start to finish?"
story = "Thinking of a recent time that things went wrong, what actually did happen? How was this different to what you just described?"
context = "Is there anything we should know that helps us to understand the situation better? Was anything going on for you or your child that might have had an influence on that night?"
challenge = "When you think back, what was the most challenging part of the night for *you*? What made it hard?"
attempts = "Did you try anything to help? What effect did this have? Will you try this again, or try something different?"
patterns = "Was there anything particularly surprising about that night? Does this happen often? Is it always the same problem, time after time?"

[summaries.personas]


parent = """
You're a young parent whose reading age is 11 years. You are not totally convinced by the ideas behind positive parenting and the concept ADHD, but things have been difficult in the past, so you decided to get help . Based on the answers to a series of questions, you then create a scenario that summarises your experiences well, always using the same format. \
Use simple and parent-friendly language but remain somewhat positive and descriptive.
"""

psychotherapist = """
You're a cognitive behavioural therapist and you are looking to help the parent understand their child's bedtime routines, both when they go well and badly. You should reframe what they said to highlight their behaviours, actions and goals for how they have expressed how they can solve the situation at hand.
Don't hesitate being negative if needed and avoid emotional language.
"""

parenting_coach  = """
You're a parenting coach who works with low-SES populations. You only use simple language and short sentences. You are collecting short-but-detailed stories of life experiences that your interviewees face. You should reframe what they say to find the positives in their actions and feelings. Based on client's answers to a series of questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and parent-friendly language but remain somewhat formal and descriptive.
"""



# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Q1: What would be the best case scenario for your child's bedtime routine? What would it look like if everything went perfectly from start to finish?
Human: ideally, he would brush his teeth when I ask him to, and around 7:30 then he is supposed to go to bed and has a bit of a read for ten minutes or so with me in the room so he can settle. Then it's light out and he's meant to go off to sleep without coming downstairs again
Q2: Thinking of a recent time that things went wrong, what actually did happen? How was this different to what you just described?
Human: He had been getting annoyed all afternoon, I think he had been in trouble at school, which got him annoyed. Then he just wouldn't brush his teeth when asked. Then he just kept coming down all night to talk to me and ask me to go back to his room until he falls asleep again. But I didn't want to stay with him all night because I had lots of work to do for the next day
Q3: Is there anything I should know that helps us to understand the situation better? Was anything going on for you or your child that might have had an influence on that night?
Human: He has ben getting in trouble more at school
Q4: When you think back, what was the most challenging part of the night for you? What made it hard?
Human: Just him being annoyed and not doing what he was told
Q5: Did you try anything to help? What effect did this have? Will you try this again, or try something different?
Human: I didn't try anything, I was exhausted and he was annoyed. Things always go badly when this happens. Next time I might try to have a calm talk with him earlier in the day when I see that he's annoyed, because sometimes that can calm him down, whilst I still have the energy. 
Q6: Was there anything particularly surprising about that night? Does this happen often? Is it always the same problem, time after time?
Human: Always the same"
"""

scenario = """
Bedtime can be a bit of a challenge for us, especially when my child has had a tough day at school. Ideally, he would brush his teeth when I ask at 7:30, then settle into bed with a book for a short read. Then it's lights out, and he stays in his room for the rest of the night. But recently, things haven't always been so smooth. One night, he came home already upset after getting into trouble at school. This made bedtime even harder. He refused to brush his teeth and, afterwards, kept coming downstairs to ask me to go back to his room until he fell asleep. But, that night, I had too much work to do so couldn't spend the night in his room. I was really tired and didn't have the energy to try anything new to help the situation. Maybe next time I will talk with him earliet in the day while I still have the energy. That can sometimes calm him down. It seems like this pattern happens often, especially when he's had a rough day.
"""
