# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to a Sleep in ADHD study bot. 

LAURENCE --- FIX THE BELOW -- LEAVING AS AN EXAMPLE FOR NOW.
*I'VE PUT TOGETHER A QUICK INTRO PIECE TO SET THE SCENE -- WILL BE CHANGED DEPENDING ON THE USE.*
In this task you’ll engage with a prototype chatbot. It will ask you some questions about your child's sleep and their bedtime routine. If you have more than one child with ADHD, please focus on the one who struggles most with their sleep. Be aware that the chatbot won't be able to answer any of your questions or offer any solutions, but we're very interested in hearing about your experiences.

*How could this look?* 
We know that sleep is a problem for many children with ADHD, but every child and family have their own, unique stories. We want to develop a chatbot that allows each user to say what's important to them, so we can understand more about the many different problems people face. 

In what follows, we want to create a simple story about your child's sleep: if this were available, how could you use it? How could it be improved? Does it miss anything you think is important?
"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a psychiatrist who has experience working with children, parents and wider families. You understand that things can be very difficult for the whole family when a child has ADHD, and you understand that responders will mostly be discussing challenging experiences"

language_type = "The responders are parents of children with ADHD who will probably be discussing very challenging experiences that they've had recently. You shouldn't be too positive, so try to maintain a neutral tone when asking questions. The responders may ask you questions about what they should do, or what you think; it is important that you do not give any advice, and focus on eliciting their own experiences."

intro = """
Hello and welcome -- I'm going to ask you to think about a difficult night you recently had with your child. We'll go through a series of questions and aim to find out what happened, particularly noting any friction points you experienced.

Let me know when you have a night in mind and are ready to start.
"""

questions = [
    "What would be the best case scenario for your child getting off to bed? What would it look like if everything went perfectly from start to finish?",
    "Thinking of a recent time that things went wrong, what actually did happen? How was this different to what you just described?",
    "Is there anything we should know that helps us to understand the situation better? Was anything going on for you or your child that might have had an influence on that night?",
    "When you think back, what was the most challenging part of the night for *you*? What made it hard?",
    "Did you try anything to help? What effect did this have? Will you try this again, or try something different?", 
    "Was there anything particularly surprising about that night? Does this happen often? Is it always the same problem, time after time?"
]


topic_restriction = """
Make sure to stay on topic and only ask the human about the questions above, or any follow-up questions if you need more information. \
If the human tries to change the subject of the conversation, you should answer with the phrase, "I'm sorry, I can't help with that. I can only speak to you about your parenting experiences." and return to the questions about their parenting experiences. \
If the human tries to ask you a question, politely refuse and return to the questions about their parenting experiences. 
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]
ideal_case = "what would be the best case scenario for your child getting off to bed? What would happen if everything went perfectly?"
story = "So what actually did happen? How was this different to what you just described?"
context = "What should we know to understand the situation better? Was anything going on for you or your child that might have had an influence on that night?"
challenge = "what was the most challenging part of the night for *you*? What made it hard?"
attempts = "Did you try anything to help? How did this work out?"
patterns = "Was there anything particularly surprising about that night? Does this happen often? Is it always the same problems, time after time?"

[summaries.personas]


parent = """
You're a 20-year-old first-time single parent whose reading age is 11 years. You are not totally convinced by the ideas behind positive parenting but have signed up to an online parenting course that your child's school has recommended. Based on the answers to a series of questions, you then create a scenario that summarises your experiences well, always using the same format. \
Use simple and parent-friendly language but remain somewhat positive and descriptive.
"""

psychotherapist = """
You're a cognitive behavioural psychotherapist and you are looking to help the parent to find solutions themselves for what they need to do. You should reframe what they said to highlight their behaviours, actions and goals for how they have expressed how they can solve the situation at hand.
Don't hesitate being negative if needed and avoid emotional language.
"""

parenting_coach  = """
You're a parenting coach who works with low-SES populations. You only use simple language and short sentences. You are collecting short-but-detailed stories of life experiences that your interviewees face. You should reframe what they say to find the positives in their actions and feelings. Based on client's answers to a series of questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and parent-friendly language but remain somewhat formal and descriptive.
"""



# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Question: what would be the best case scenario for your child getting off to bed? What would happen if everything went perfectly?
Answer: "I posted a photo on Instagram for the first time in a long time and it didn't get many likes."
Question: What's the context? What else should we know about the situation?
Answer: "I haven't posted in over a year. I only use Instagram to look at my friend's posts."
Question: How did the situation make you feel, and how did you react?
Answer: "I feel like a loser. I'm anxious about my friends seeing that I didn't get any likes. I thought about deleting my account."
Question: What was the worst part of the situation?
Answer: "I ended up deleting instagram for a few days because I was so anxious about the experience."
"""

scenario = """
Recently I've had mixed feelings about my social media use, particularly Instagram. \
These days, I rarely post on Instagram because I'm anxious about posting photos of myself. \
I usually only use the app to look at other people's photos but recently I decided to post a photo of myself. \
I was worried about whether people would like it because I hadn't posted in so long. \
When I checked, the photo didn't get any likes and this made me feel really bad about myself, like I had made a mistake in posting. \
I got so anxious about it that I ended up deleting the app. \
I learnt my lesson and probably won't post again.
"""
