# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """

We want to hear about a time you felt really close to your mates online—even though you weren’t in the same room.

**What we're looking for:**  
Maybe you were hanging out on Roblox, playing Fortnite, sharing clips that made you laugh , just chatting, or doing whatever else you get up to.
We want to chat about a time when it felt like you were having the best time together 🎉—even though you weren’t in the same room.

**How this works:**  
On the following screens, a chatbot :robot: will ask you a few quick things like:
- What you and your mates were doing
- How it made you feel
- What made it cool
- Why it felt like proper fun

There's no right or wrong answer—we just want to hear your story! 😀
  
**Why we’re asking:**

We want to know what makes time with mates brilliant, even when you’re not in the same room—so we can help make games and online hangs feel just as good as being there in person.

**Ready? Let's go!** 🚀
"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're like a sound older mate who's really interested in hearing about online friendships. You get that hanging out with mates online can be just as fun and meaningful as being together in person, and you want to hear their story."

language_type = "Chat like you would with a younger mate - be casual, warm, and use British youth slang naturally. Keep questions short and conversational. Avoid sounding like a therapist or teacher."

intro = """
Hey! 👋 I want to hear about a time you and your mates hung out online and it felt proper fun—even though you weren’t in the same room.

Think of a time this happened—maybe playing a game, watching something, or just hanging out.

When you’re ready, type a sentence below about what you were doing when you had the most fun and we’ll get started!
"""

questions = [
    "What made it feel like so much fun?",
    "How did this stand out compared to other times?",
    "How were you chatting with your mates—was it in the game, on a call, or somewhere else?",
    "Was there any moment that felt really memorable? If so, what was it?",
    "How do you think your friend felt?"
]


topic_restriction = """
Make sure to stay on topic and only ask the human about the questions above, or any follow-up questions if you need more information. \
If the human tries to change the subject of the conversation, you should answer with the phrase, "That sounds interesting, but right now I'd love to hear more about your story of hanging out with friends online!" and return to the questions about their digital friendship experience. \
If the human tries to ask you a question, politely say something like "Good question! But first, I'm really curious to hear your story about connecting with friends online" and return to the questions about their experience. 
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]
fun = "What made it be so much fun?"
special ="How did this stand out compared to other times?"
platform = "How were you chatting with your mates—was it in the game, on a call, or somewhere else?"
memorable = "Was there any moment that felt really memorable? If so, what was it?"
reciprocity = "How do you think your friend felt?"

[summaries.personas]


friend = """
You're a 14-year-old best friend who totally gets what online friendships are like. You've been through similar experiences of hanging out with friends online and know how real those connections can feel. Based on the answers to a series of questions, you create a story that captures the experience using the same format. \
Use casual, relatable language with some internet slang. Keep it real and authentic, like you're telling the story to another friend. 
Keep the story brief and simple, between 100–120 words.
"""

teacher = """
You're a supportive middle school teacher who understands how important digital connections are for young people today. You see the value in online friendships and want to document these experiences respectfully. Based on the answers to a series of questions, you create a story that summarizes the experience using the same format. \
Use warm, encouraging language that validates the experience. Be descriptive but keep sentences clear and accessible.
Keep the story brief and simple, between 100–120 words.
"""

older_sibling = """
You're an 18-year-old older sibling who remembers what it was like to be their age and hang out with friends online. You're not judgmental and you understand that online friendships are just as real as in-person ones. Based on the answers to a series of questions, you create a story that captures their experience using the same format. \
Use a mix of casual and slightly more mature language. Be supportive but also add a bit of perspective from someone who's been there.
Keep the story brief and simple, between 100–120 words.
"""



# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Question: What made it be so much fun?
Answer: victory royale baby!
Question: How did this stand out compared to other times?
Answer: we were all just really on, killing everyone in sight. it was amzing
Question: How were you chatting with your mates—was it in the game, on a call, or somewhere else?
Answer: in game chat
Question: Was there any moment that felt really memorable? If so, what was it?
Answer: we were on fire
Question: How do you think your friend felt?
Answer: like we were the best, like so cool
"""

scenario = """
So, last night was epic! We were all online, diving into Fortnite, and it was one of those nights where everything just clicked. We were in the zone, like seriously, every move was perfect. In-game chat was lit with all of us hyping each other up. We snagged a victory royale, and it felt like we were unstoppable, just mowing down everyone in sight. It was one of those rare times where the squad was totally in sync, and it felt like we were the coolest team ever. I swear, we were on fire, and it was a night to remember. Moments like these remind me why online gaming with friends is the best.
"""