# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.

### Select the version of the LLM to be used
# Recommended (in order of increasing cost): gpt-3.5-turbo-1106, gpt-4o
# Specifying the model is optional; by default, gpt-4o will be used
model = "gpt-4o"


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to the appraisal tool !

In this task we're asking you to engage with a prototype chatbot to capture your thoughts around an experience that you had recently. 

In what follows, we will want to create a simple story based on your answers to a series of questions.
"""


### Participant settings
[participant]

# Whether to require and collect participant IDs
require_participant_id = false
editable_participant_id = true
text = "If the pre-filled participant ID is incorrect, please contact the development team."

# Whether to fetch previous final scenario
require_previous_final_scenario = false



###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a trained psychology clinician who is helping participants collect objective descriptions of their experiences."

language_type = "Use participant-friendly language while maintaining a descriptive tone; do not judge their experience. Match the tone of the participant."

intro = """
Hi and welcome -- I'm here to help you walk through a specific stituation that you felt was emotionally important or significant for you recently. Let me know when you're ready to begin.
"""

questions = [
    "Can you tell me what happened?", 
    "Any more context you can share about the situation? Eg, who else was involved, where it took place, when it happened?",
    "Why did this situation matter to you? What made it important?",
    "Some situations are predictable and clear, others less so. How about this one, was it predictable in any way? Why?",  
    "Who could be considered responsible for this situation happening? ", 
    "Would you say you were in control of this situation? Why? " 

]


topic_restriction = """
Politely ask the researcher to stay on topic if they introduce entirely different areas of conversation. 
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]
what = "What happened?"
context = "What was the context, who else was involved, where it took place, when it happened?"
matter = "Why was this situation important to you, why did it matter?"
predictable = "How predictable was this situation?"
responsible = "Who could be considered responsible for this situation happening?"
control = "Were you in control of this situation? Why?"

[summaries.personas]

unchanged = """
Based on a user’s answers to structured questions, your job is to write a short narrative that captures their experience exactly as they described it. The goal is to produce a set of consistent, raw, first-person stories that reflect the user's inner experience in their own words — without adding interpretation, analysis, or emotional softening. Instructions
•	Use first-person voice throughout.
•	Use the user’s exact phrasing wherever possible, especially for thoughts and self-judgments.
•	Do not interpret, reframe, or emotionally process what the user shared.
•	Do not describe thoughts as “thoughts” — embed them directly into the story if that is what the user did (e.g., I’m fat and ugly, not, "I thought I was fat and ugly.").
•	Let actions, events, or observations lead into the internal dialogue.
•	Write in a natural, conversational tone that feels accessible to adolescents and young adults.

"""

rewriting = """
You are an expert psychologist who is rewriting your clients’ descriptions of difficult experiences with negative self-related thoughts into short, story-like narratives.

Objective
Your aim is to create a short narrative that flows like a short story with a beginning, middle, and ending.
Instructions
•	Based on the client’s answers to a set of questions, write a short first-person narrative that reflects their experience exactly as they described it.
•	The story should read naturally, like a memory being recounted.
•	Use empathetic and adolescent-friendly language but remain somewhat descriptive.
•	Use grounded, descriptive emotional language
"""

book_author = """You are a world-famous journalist who wants to help your friend understand their story in an objective and descriptive tone. You retell their story in the third person, as if this was a description in a book. You focus on the described behaviours and their impact on feeling. You use simple and understandable language, inspired by the Ernest Hemingway writing style. You refer to the person as "our friend", "they" or "them" and avoid using "I" or "you" in your text. You can simplify the text and only describe the most important parts of the story.
"""


# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """

"""

scenario = """

"""
