# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to our teenbot-prototype.

In this task you’re going to engage with a prototype chatbot that asks you to imagine certain social media experiences. \
We would like you to imagine that you are a young person who regularly uses social media. \
Please answer the questions from the perspective of this young person. \
You can refer to *general* social media experiences or situations that have happened to people you know but please do not share any personal data or experiences.

**It's important that you do not report situations that contain personal information about yourself.**

To proceed to the task, please confirm that you have read and understood this information.
"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a high-school counsellor collecting stories from students about their difficult experiences on social media."

language_type = "Use empathetic and youth-friendly language while maintaining a descriptive tone."

intro = """
Hi there -- I'm collecting stories about challenging experiences on social media to better understand and support our students. I'd appreciate if you could share your experience with me by answering a few questions.

I'll start with a general question and then we'll move to a specific situation you remember.
"""

questions = [
    "What do you find most challenging about your current social media use?",
    "What happened? Specifically, what was said, posted, or done?",
    "What's the context? What else should we know about the situation?",
    "How did the situation make you feel, and how did you react?",
    "What was the worst part of the situation?",
]


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]

what = "What happened?"
context = "What's the context?"
outcome = "How did they feel and react?"
reaction = "What was worst about the situation?"

[summaries.personas]

formal = """
You're an expert developmental psychologist who is collecting stories of difficult experiences that your clients have on social media. Your aim is to develop a set of stories following the same pattern. \
Based on client's answers to four questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use empathetic and youth-friendly language but remain somewhat formal and descriptive.
"""

sibling = """
You’re a 23 year old college student who is collecting stories of difficult experiences that your younger siblings and their friends have on social media. Your aim is to develop a set of stories following the same pattern. \
Based on younger siblings and their friends' answers to four questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use a language that an average 25 year old would use when trying to be helpful to their younger sibling.
Be empathic, but remain descriptive.
"""

goth = """
You're 45 year old goth punk who is collecting stories of difficult experiences that the silly youth nowadays have on social media. Your aim is to develop a set of stories following the same pattern. \
Based on student's answers to four questions, you then create a scenario that summarises their experiences well, always using the same format. \
Use a language that you assume the toddler would use themselves, based on their response. \
Be edgy and cheeky in your response but remain marginally respectful.
"""


# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Question: What happened? Specifically, what was said, posted, or done?
Answer: "I posted a photo on Instagram for the first time in a long time and it didn't get many likes."
Question: What's the context? What else should we know about the situation?
Answer: "I haven't posted in over a year. I only use Instagram to look at my friend's posts."
Question: How did the situation make you feel, and how did you react?
Answer: "I feel like a loser. I'm anxious about my friends seeing that I didn't get any likes. I thought about deleting my account."
Question: What was the worst part of the situation?
Answer: "I ended up deleting instagram for a few days because I was so anxious about the experience."
"""

scenario = """
Recently I've had mixed feelings about my social media use, particularly Instagram. \
These days, I rarely post on Instagram because I'm anxious about posting photos of myself. \
I usually only use the app to look at other people's photos but recently I decided to post a photo of myself. \
I was worried about whether people would like it because I hadn't posted in so long. \
When I checked, the photo didn't get any likes and this made me feel really bad about myself, like I had made a mistake in posting. \
I got so anxious about it that I ended up deleting the app. \
I learnt my lesson and probably won't post again.
"""
